[tool.poetry]
name = "polus-plugins-visualization-ome-to-microjson"
version = "0.1.2-dev"
description = "This plugin create a microjson of polygon coordinates of binary segmentations"
authors = ["Hamdah Shafqat abbasi  <hamdahshafqat.abbasi@nih.gov>"]
readme = "README.md"
packages = [{include = "polus", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
bfio = {version = "2.3.2", extras = ["all"]}
scyjava = "^1.9.1"
typer = "^0.7.0"
scipy = ">=1.8,<1.9.2"
filepattern = "^2.0.1"
tqdm = "^4.65.0"
microjson = "^0.1.9"
fastapi = "^0.103.1"
llvmlite = "^0.40.1"
vaex = "^4.17.0"
scikit-image = "^0.20.0"


[[tool.poetry.source]]
name = "test"
url = "https://test.pypi.org/simple/"
default = false
secondary = true

[tool.poetry.group.dev.dependencies]
bump2version = "^1.0.1"
flake8 = "^6.0.0"
pre-commit = "^3.2.1"
flake8-docstrings = "^1.7.0"
black = "^23.3.0"
mypy = "^1.1.1"
pytest = "^7.2.2"
ruff = "^0.0.270"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
