[tool.poetry]
name = "polus-plugins"
version = "0.1.0"
description = ""
authors = ["nicholas-schaub <nick.schaub@nih.gov>"]
readme = "README.md"
packages = [{include = "polus", from = "src"}]

[tool.mypy]
exclude = "src/polus"

[tool.poetry.dependencies]
python = "^3.9"
python-on-whales = "^0.57.0"
pygithub = "^1.57"
pydantic = "^1.10.4"
tqdm = "^4.64.1"
xmltodict = "^0.13.0"
fsspec = "^2023.1.0"
click = "^8.1.3"

[tool.poetry.group.dev.dependencies]
nox = "^2022.11.21"
pre-commit = "^3.0.4"
pydantic-to-typescript = "^1.0.10"
datamodel-code-generator = "^0.17.1"
black = "^23.1.0"
flake8 = "^6.0.0"
poetry = "^1.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
