[tool.poetry]
name = "polus-plugins-transforms-images-binary-operations"
version = "0.4.2"
description = ""
authors = ["nicholas-schaub <nick.schaub@nih.gov>", "Madhuri Vihani"]
readme = "README.md"
packages = [{include = "polus", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
bfio = {version = "2.1.9", extras = ["all"]}
typer = "^0.7.0"
filepattern = "^2.2.7"
opencv-python = "^4.7.0.72"
preadator = "^0.2.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
mypy = "^1.0.1"
black = "^23.1.0"
flake8 = "^6.0.0"
pre-commit = "^3.1.0"
bump2version = "^1.0.1"
flake8-docstrings = "^1.7.0"

[[tool.poetry.source]]
name = "test"
url = "https://test.pypi.org/simple/"
secondary = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
