[tool.poetry]
name = "polus-python-template2"
version = "1.1.0-dev0"
description = ""
authors = ["Nick Schaub <nick.schaub@nih.gov>", "Antoine Gerardin <antoine.gerardin@gmail.com>"]
readme = "README.md"
packages = [{include = "polus_python_template2"}]

[tool.poetry.dependencies]
python = "^3.9.16"

[tool.poetry.group.dev.dependencies]
pip = "^23.0.1"
cookiecutter = "1.7.2"
jinja2_ospath = "0.3.0"
bump2version = "^1.0.1"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
