[package]
authors = ["Najib Ishaq <najib.ishaq@axleinfo.com>"]
name = "ftl-rust"
version = "0.1.0"
edition = "2018"

[lib]
name = "ftl_rust"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.14", features = ["extension-module"] }
rayon = "1.0"
ndarray = { version = "0.15", features = ["rayon"] }
numpy = "0.14"

[dev-dependencies]
memmap2 = "0.3"
ndarray-npy = "0.8"
criterion =  { version = "^0.3", features = ["html_reports"] }

[[bench]]
name = "ftl_rust"
harness = false