[tool.poetry]
name = "polus-plugins-utils-bbbc-download-plugin"
version = "0.1.0-dev1"
description = ""
authors = [
    "Saket Prem <saket.prem@axleinfo.com>", 
    "Matthew McIntyre <Matthew.McIntyre@axleinfo.com>"
    ]
readme = "README.md"
packages = [{include = "polus", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.9,<4"
typer = "^0.9.0"
pyarrow = "11.0.0"
scikit-image = "0.20.0"
vaex = "4.16.0"
bfio = "2.3.1.dev0"
beautifulsoup4 = "4.12.0"
numpy = "1.24.2"
pandas = "1.5.3"
requests = "2.28.2"
pydantic = "1.10.7"
bump2version = "1.0.1"
mypy = "1.0.1"
tqdm = "^4.65.0"
pytest = "^7.4.0"
xmlschema = "^2.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
