[project]
name = "ome_zarr_autosegmentation_plugin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.1.0",
    "torchvision>=0.16.0",
    "greenlet>=3.1.1",
    "ome-zarr>=0.9.0",
    "bfio>=2.3.6",
    "sam2>=1.1.0",
    "typer>=0.15.1",  
]

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch" }
torchvision = { index = "pytorch" }

[dependency-groups]
dev = [
    "ruff>=0.8.0",
]

[tool.ruff.lint]
extend-select = ["I"]
