[tool.poetry]
<<<<<<< HEAD
<<<<<<< HEAD
name = "polus-plugins-transforms-images-image-assembler"
<<<<<<< HEAD
version = "1.4.0-dev0"
description = "A scalable image assembler plugin."
authors = ["Nick Schaub <nick.schaub@nih.gov>", "Antoine Gerardin <antoine.gerardin@gmail.com>"]
=======
name = "polus-transforms-images-image-assembly-plugin"
<<<<<<< HEAD
<<<<<<< HEAD
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
>>>>>>> cbaf94c (update/image-assembler-plugin)
=======
version = "1.2.0-dev0"
description = "A scalable image assembling plugin."
authors = ["Nick Schaub <nick.schaub@nih.gov>"]
>>>>>>> f5f7212 (fix: update to version 1.2.0-dev0)
=======
=======
name = "polus-plugins-transforms-images-image-assembler"
>>>>>>> de6ea1d (Update: update to new plugin standard:)
version = "1.2.1-dev0"
=======
version = "1.3.0-dev0"
>>>>>>> 254a68a (update : update to new standards.)
description = "A scalable image assembler plugin."
authors = ["Nick Schaub <nick.schaub@nih.gov>", "Antoine Gerardin <antoine.gerardin@gmail.com>"]
>>>>>>> 83c08da (update: - refactor variables names to snake case)
readme = "README.md"
packages = [{include = "polus", from = "src"}]

[tool.poetry.dependencies]
<<<<<<< HEAD
<<<<<<< HEAD
python = "^3.9.15"
bfio = {version = "2.1.9", extras = ["all"]}
<<<<<<< HEAD
filepattern = "^2.0.1"
preadator = "0.3.0.dev1"
=======
python = "^3.10"
=======
python = "^3.9.15"
>>>>>>> f5f7212 (fix: update to version 1.2.0-dev0)
bfio = {version = "2.1.9", extras = ["all"]}
filepattern = {version = "2.2.7", source = "test"}
preadator = "^0.2.0"
>>>>>>> cbaf94c (update/image-assembler-plugin)
=======
filepattern = "1.4.7"
preadator = "0.3.0.dev1"
>>>>>>> 254a68a (update : update to new standards.)
typer = "^0.7.0"
pip = "^23.0.1"
install = "^1.3.5"


[[tool.poetry.source]]
name = "test"
url = "https://test.pypi.org/simple/"
default = false
secondary = true


[tool.poetry.group.dev.dependencies]
bump2version = "^1.0.1"
flake8 = "^6.0.0"
pre-commit = "^3.2.1"
flake8-docstrings = "^1.7.0"
black = "^23.3.0"
mypy = "^1.1.1"
<<<<<<< HEAD
<<<<<<< HEAD
pytest = "^7.2.2"
ruff = "^0.0.270"
<<<<<<< HEAD
=======
>>>>>>> cbaf94c (update/image-assembler-plugin)
=======
pytest = "^7.2.2"
>>>>>>> 36a8639 (feat: add unit tests)
=======
>>>>>>> 254a68a (update : update to new standards.)

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
