name: Docker Build and Push

on:
  workflow_call:
    inputs:
      matrix:
        description: 'JSON-encoded matrix'
        required: true
        type: string
      push:
        description: 'Whether to push the image to Docker Hub'
        required: true
        type: boolean
    secrets:
      DOCKER_USERNAME:
        description: 'Docker Hub username'
        required: true
      DOCKER_PASSWORD:
        description: 'Docker Hub password'
        required: true

permissions:
  contents: read

jobs:
  docker:
    name: Docker "${{ matrix.package_name }}"
    strategy:
      matrix: ${{fromJson(inputs.matrix)}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get | Docker Tag
        id: docker_tag
        run: |
          package_dir="${{ matrix.package_dir }}"
          version=$(cat ${package_dir}/VERSION)
          tag=polusai/${{ matrix.package_name }}:${version}
          echo "tag=${tag}" >> $GITHUB_OUTPUT
      - name: Setup | Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login | DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Check | Image exists
        run: |
          tag=${{ steps.docker_tag.outputs.tag }}
          docker pull ${tag} > /dev/null \
              || echo "failed" \
              && echo "::error::${tag} already exists on DockerHub" && exit 1
      - name: Publish | Docker Image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:${{ matrix.package_dir }}"
          push: ${{ inputs.push }}
          tags: ${{ steps.docker_tag.outputs.tag }}
