name: Package Release

on:
  push:
    branches:
      - master
      - main
      - dev

permissions:
  contents: write

jobs:
  package-filter:
    name: Filter for updated package
    uses: ./.github/workflows/package-filter.yml

  package-release:
    name: Bump release version of updated package
    if: github.repository == 'polusai/polus-plugins'
    runs-on: ubuntu-latest
    needs: package-filter
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install bump2version
        run: |
          python -m pip install --upgrade pip
          pip install bump2version
      - name: Bump Version on all updated packages
        run: |
          CUR_DIR=$(pwd)

          for package_dir in ${{ needs.package-filter.outputs.package_dirs }}
          do
            cd "$CUR_DIR/$package_dir"
            bump2version release --no-commit
          done

          cd "$CUR_DIR"
      - name: Commit and push all changed files
        env:
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          PKG_NAMES=""
          for package_dir in ${{ needs.package-filter.outputs.package_dirs }}
          do
            PKG_NAMES="$PKG_NAMES $(basename $package_dir)"
          done

          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git commit -a -m "build: Bumped release version for $PKG_NAMES"
          git push
