name: Package Filter

on:
  workflow_call:
    inputs:
      num-commits:
        description: "The of commits to check for updated packages. If 0, the action will assume that it is running on a non-master branch and will check all commits on the current branch against the master branch. For any larger value, the action will check the last n commits for any updated packages."
        required: true
        default: 0
        type: number
      ignore-missing-dev:
        description: "If true, the action will ignore packages that do not have a dev version. Otherwise, the action will fail if any package does not have a dev version."
        required: true
        default: false
        type: boolean
    outputs:
      matrix:
        description: "The directories containing the updated packages"
        value: ${{ jobs.package-filter.outputs.matrix }}

permissions:
  contents: read

jobs:
  package-filter:
    name: Filter for updated packages
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.package-filter.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          persist-credentials: false
      - name: Find Updated Packages
        id: package-filter
        run: |
          PACKAGE_DIRS=""
          COMPANION_FILES="VERSION Dockerfile .bumpversion.cfg plugin.json"

          # echo the base ref
          base_ref=${{ github.base_ref }}
          if [[ -z "$base_ref" ]]
          then
            base_ref="master"
            echo "::warning::Action not running on PR, defaulting to base branch to master"
          fi
          echo "The base ref is $base_ref"

          # Get the comparison point in the repo
          if [[ ${{ inputs.num-commits }} == 0 ]]
          then
            comparison_point="origin/${base_ref}"
          else
            comparison_point="HEAD~${{ inputs.num-commits }}"
          fi
          echo "The comparison point is ${comparison_point}"

          for changed_file in $(git diff --name-only ${comparison_point}...)
          do
            pkg_dir=$(dirname ${changed_file})

            # Exclude the root directory
            if [[ "$pkg_dir" == "." ]]
            then
              continue
            fi

            # Check if the changed file is a pyproject.toml file
            if [[ "$(basename ${changed_file})" == *"pyproject.toml"* ]]
            then
              pkg_dir=$(dirname ${changed_file})

              # Check that the package has all the necessary companion files
              for companion_file in $COMPANION_FILES
              do
                if [[ ! -f "$pkg_dir/$companion_file" ]]
                then
                  echo "::error::${pkg_dir} does not have a $companion_file file" && exit 1
                fi
              done

              # Check that the version is a dev version
              if [[ "$(cat ${pkg_dir}/VERSION)" != *"dev"* ]]
              then
                msg="${pkg_dir} does not have a dev version"
                ${{ inputs.ignore-missing-dev }} && echo "::warning::${msg}" || $(echo "::error::${msg}" && exit 1)
              fi

              PACKAGE_DIRS="$PACKAGE_DIRS ${pkg_dir}"
            fi
          done

          # Check if any packages were found
          echo "The updated packages are $PACKAGE_DIRS"
          if [[ -z "$PACKAGE_DIRS" ]]
          then
            echo "::error::No updated packages were found" && exit 1
          fi

          # Convert the package directories to JSON for the output matrix
          JSON="{\"include\": ["
          for package_dir in $PACKAGE_DIRS
          do
            package_name=$(basename $package_dir)
            JSON_LINE="{\"package_dir\": \"${package_dir}\", \"package_name\": \"${package_name}\"},"
            # Add the JSON line to the JSON string if it is not already included
            if [[ ! "$JSON" == *"$JSON_LINE"* ]]
            then
              JSON="$JSON$JSON_LINE"
            fi
          done

          # Remove trailing comma and add closing brackets
          if [[ $JSON == *, ]]
          then
            JSON="${JSON%?}"
          fi
          JSON="$JSON]}"

          # Set the output
          echo "matrix=$( echo "$JSON" )" >> $GITHUB_OUTPUT
