name: Package tests

on:
  pull_request:
    branches:
      - main
      - master
      - dev
  push:
    branches-ignore:
      - main
      - master
      - dev
  workflow_call:
    inputs:
      num-commits:
        description: "The of commits to check for updated packages. If 0, the action will assume that it is running on a non-master branch and will check all commits on the current branch against the master branch. For any larger value, the action will check the last n commits for any updated packages."
        required: true
        default: 0
        type: number
    secrets:
      DOCKER_USERNAME:
        description: 'Docker Hub username'
        required: true
      DOCKER_TOKEN:
        description: 'Docker Hub password'
        required: true

permissions:
  contents: read

jobs:
  package-filter:
    name: Filter for updated package
    uses: ./.github/workflows/package-filter.yml
    with:
      num-commits: ${{ github.event.inputs.num-commits }}

  tests:
    name: Test "${{ matrix.package_name }}"
    needs: package-filter
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.package-filter.outputs.matrix)}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
      - name: Install pre-commit
        run: |
          pip install pre-commit
      - name: Run pre-commit hooks and check for changes
        run: |
          cd "${{ matrix.package_dir }}"

          poetry run pre-commit run --files ./**/**
          if [[ $(git status --porcelain) ]]
          then
            echo "::error::pre-commit hooks failed for ${{ matrix.package_name }}" && exit 1
          fi
      - name: Run tests
        run: |
          package_dir=${{ matrix.package_dir }}
          cd $package_dir

          poetry install
          poetry run pytest -v

  docker:
    name: Build Docker images
    needs: [package-filter, tests]
    uses: ./.github/workflows/docker.yml
    with:
      matrix: ${{ needs.package-filter.outputs.matrix }}
      push: false
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  # docker:
  #   name: Docker "${{ matrix.package_name }}"
  #   needs: [package-filter, tests]
  #   uses: ./.github/workflows/docker.yml
  #   with:
  #     matrix: ${{ needs.package-filter.outputs.matrix }}
  #     push: false
  #   secrets:
  #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #     DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
